services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    ports: ["5432:5432"]

  petclinic:
    build: .
    ports: ["8080:8080"]
    volumes:
      - ./cr:/app/cr
    depends_on:
      - postgres
    privileged: true
